language: node_js
node_js:
  - 21.6.1

cache:
  directories:
    - .template/node_modules
    - .template/functions/node_modules

before_install:
  - yarn create-react-app demo-app --template lnk
  - rm -rf link-app/continuous_deployment
  - mkdir -p link-app/continuous_deployment
  - cp -R packages/lnk-shell/cra-template-lnk/template/continuous_deployment link-app
  - cd link-app
  - chmod +x ./continuous_deployment/before_install.sh
  - ./continuous_deployment/before_install.sh

before_script:
  - yarn test --passWithNoTests
  - chmod +x ./continuous_deployment/build.sh
  - travis_wait 40 ./continuous_deployment/build.sh

script:
  - chmod +x ./continuous_deployment/deploy_hosting.sh
  - travis_wait 40 ./continuous_deployment/deploy_hosting.sh
  - chmod +x ./continuous_deployment/deploy_functions.sh
  - travis_wait 40 ./continuous_deployment/deploy_functions.sh
  - chmod +x ./continuous_deployment/browser_stack.sh
  - travis_wait 40 ./continuous_deployment/browser_stack.sh
